name = "EenAllesCobblemon SMP"
author = "EenAllesKanaal SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49f867a2a8594721b5f02344a293f74aaac41671263d1144ed21e0b0adeac591"

[versions]
minecraft = "1.21.1"
fabric = "0.18.4"
