#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 09 22:09:16 CEST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=Solas Shader V3.5.zip
