# Don't change this! Version used to track needed updates.
version = 1
disableParticles = false
byTypeReductions = {  }
maxParticlesPerSheet = 3600
particleRenderDistanceMultiplier = 0.7507697610294117
asynchronousTicking = false
cullingBlacklist = [  ]
cullingBehavior = "BOUNDING_BOX"
reduceAllChance = 0.0
reduceDecreasedChance = 0.0
turnOffPotionParticlesV2 = [
    "SELF"
]